export const DEPARTMENTS = [
  'QA Engineer',
  'Systems Administrator',
  'Cloud Engineer',
  'Operations Analyst',
  'Social Media Manager',
  'Senior Software Engineer',
  'Finance Analyst',
  'Technical Writer',
  'UI Designer',
  'Manufacturing Technician',
  'Office Administrator',
  'Security Analyst',
  'Territory Manager',
  'Business Development Manager',
  'Accountant',
  'Support Engineer',
  'Data Analyst',
  'Billing Specialist',
  'Solutions Architect',
  'HR Generalist',
  'R&D Scientist',
  'Supply Chain Coordinator',
  'Data Engineer',
  'Product Manager',
  'Procurement Specialist',
  'Facilities Manager',
  'Sales Manager',
  'Network Engineer',
  'Graphic Designer',
  'Customer Success Manager',
  'UX Designer',
  'Software Engineer',
  'Inside Sales Associate',
  'Digital Marketing Manager',
  'Sales Representative',
  'Legal Counsel',
  'Marketing Specialist',
  'Research Associate',
  'Content Strategist',
  'Field Service Engineer',
  'Business Analyst',
  'Operations Manager',
  'Project Manager',
  'DevOps Engineer',
  'Compliance Specialist',
  'IT Support Specialist',
  'Recruiter',
  'Training Coordinator',
];

export const LOCATIONS = [
  'Arlington',
  'Bakersfield',
  'Virginia Beach',
  'Toledo',
  'Columbus',
  'New Orleans',
  'Jersey City',
  'St. Petersburg',
  'Greensboro',
  'Laredo',
  'Seattle',
  'Chula Vista',
  'Stockton',
  'San Diego',
  'San Jose',
  'Santa Ana',
  'Oklahoma City',
  'Orlando',
  'Washington',
  'Baltimore',
  'Milwaukee',
  'Dallas',
  'Newark',
  'Tampa',
  'Atlanta',
  'Jacksonville',
  'Pittsburgh',
  'Denver',
  'Long Beach',
  'Fort Wayne',
  'Anaheim',
  'Philadelphia',
  'Wichita',
  'Oakland',
  'Fresno',
  'Detroit',
  'Saint Paul',
  'Nashville',
  'Mesa',
  'Irvine',
  'New York',
  'Indianapolis',
  'Albuquerque',
  'Minneapolis',
  'Omaha',
  'Tucson',
  'Riverside',
  'Aurora',
  'Chandler',
  'Chicago',
  'Fort Worth',
  'Kansas City',
  'Memphis',
  'El Paso',
  'Portland',
  'Henderson',
  'Cleveland',
  'Sacramento',
  'San Francisco',
  'Raleigh',
  'Las Vegas',
  'Anchorage',
  'Charlotte',
  'St. Louis',
  'Los Angeles',
  'Boston',
  'Louisville',
  'Cincinnati',
  'Colorado Springs',
  'Houston',
  'Corpus Christi',
  'Plano',
  'Honolulu',
  'Tulsa',
  'San Antonio',
  'Miami',
  'Lincoln',
  'Durham',
  'Phoenix',
  'Madison',
  'Lexington',
  'Austin',
];
