export let OlympicsData: Object[]= 
[
  {
    "id": "OLY-0001",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "100m Men",
    "medalType": "Gold",
    "athleteName": "Maurice Greene",
    "country": "United States",
    "countryCode": "USA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0002",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "100m Men",
    "medalType": "Silver",
    "athleteName": "Ato Boldon",
    "country": "Trinidad and Tobago",
    "countryCode": "TTO",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0003",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "100m Men",
    "medalType": "Bronze",
    "athleteName": "Obadele Thompson",
    "country": "Barbados",
    "countryCode": "BAR",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0004",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "200m Men",
    "medalType": "Gold",
    "athleteName": "Konstantinos Kenteris",
    "country": "Greece",
    "countryCode": "GRE",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0005",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "200m Men",
    "medalType": "Silver",
    "athleteName": "Darren Campbell",
    "country": "Great Britain",
    "countryCode": "GBR",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0006",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "400m Men",
    "medalType": "Gold",
    "athleteName": "Michael Johnson",
    "country": "United States",
    "countryCode": "USA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0007",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "400m Women",
    "medalType": "Gold",
    "athleteName": "Cathy Freeman",
    "country": "Australia",
    "countryCode": "AUS",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0008",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "400m Women",
    "medalType": "Silver",
    "athleteName": "Lorraine Graham",
    "country": "Jamaica",
    "countryCode": "JAM",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0009",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "400m Women",
    "medalType": "Bronze",
    "athleteName": "Katharine Merry",
    "country": "Great Britain",
    "countryCode": "GBR",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0010",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "800m Men",
    "medalType": "Gold",
    "athleteName": "Nils Schumann",
    "country": "Germany",
    "countryCode": "GER",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0011",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "1500m Men",
    "medalType": "Gold",
    "athleteName": "Noah Ngeny",
    "country": "Kenya",
    "countryCode": "KEN",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0012",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "1500m Men",
    "medalType": "Silver",
    "athleteName": "Hicham El Guerrouj",
    "country": "Morocco",
    "countryCode": "MAR",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0013",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "5000m Men",
    "medalType": "Gold",
    "athleteName": "Million Wolde",
    "country": "Ethiopia",
    "countryCode": "ETH",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0014",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "10000m Men",
    "medalType": "Gold",
    "athleteName": "Haile Gebrselassie",
    "country": "Ethiopia",
    "countryCode": "ETH",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0015",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "110m Hurdles Men",
    "medalType": "Gold",
    "athleteName": "Anier Garcia",
    "country": "Cuba",
    "countryCode": "CUB",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0016",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "400m Hurdles Men",
    "medalType": "Gold",
    "athleteName": "Angelo Taylor",
    "country": "United States",
    "countryCode": "USA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0017",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Marathon Men",
    "medalType": "Gold",
    "athleteName": "Gezahgne Abera",
    "country": "Ethiopia",
    "countryCode": "ETH",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0018",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Marathon Women",
    "medalType": "Gold",
    "athleteName": "Naoko Takahashi",
    "country": "Japan",
    "countryCode": "JPN",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0019",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Long Jump Men",
    "medalType": "Gold",
    "athleteName": "Ivan Pedroso",
    "country": "Cuba",
    "countryCode": "CUB",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0020",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Triple Jump Men",
    "medalType": "Gold",
    "athleteName": "Jonathan Edwards",
    "country": "Great Britain",
    "countryCode": "GBR",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0021",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Pole Vault Men",
    "medalType": "Gold",
    "athleteName": "Nick Hysong",
    "country": "United States",
    "countryCode": "USA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0022",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Pole Vault Women",
    "medalType": "Gold",
    "athleteName": "Stacy Dragila",
    "country": "United States",
    "countryCode": "USA",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0023",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "High Jump Men",
    "medalType": "Gold",
    "athleteName": "Sergey Klyugin",
    "country": "Russia",
    "countryCode": "RUS",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0024",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Discus Men",
    "medalType": "Gold",
    "athleteName": "Virgilijus Alekna",
    "country": "Lithuania",
    "countryCode": "LTU",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0025",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Javelin Men",
    "medalType": "Gold",
    "athleteName": "Jan Zelezny",
    "country": "Czech Republic",
    "countryCode": "CZE",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0026",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Hammer Men",
    "medalType": "Gold",
    "athleteName": "Szymon Ziolkowski",
    "country": "Poland",
    "countryCode": "POL",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0027",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Decathlon Men",
    "medalType": "Gold",
    "athleteName": "Erki Nool",
    "country": "Estonia",
    "countryCode": "EST",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0028",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "20km Walk Men",
    "medalType": "Gold",
    "athleteName": "Robert Korzeniowski",
    "country": "Poland",
    "countryCode": "POL",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0029",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "50km Walk Men",
    "medalType": "Gold",
    "athleteName": "Robert Korzeniowski",
    "country": "Poland",
    "countryCode": "POL",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0030",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Long Jump Women",
    "medalType": "Gold",
    "athleteName": "Heike Drechsler",
    "country": "Germany",
    "countryCode": "GER",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0031",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Athletics",
    "event": "Heptathlon Women",
    "medalType": "Gold",
    "athleteName": "Denise Lewis",
    "country": "Great Britain",
    "countryCode": "GBR",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0032",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Swimming",
    "event": "400m Freestyle Men",
    "medalType": "Gold",
    "athleteName": "Ian Thorpe",
    "country": "Australia",
    "countryCode": "AUS",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0033",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Swimming",
    "event": "200m Freestyle Women",
    "medalType": "Gold",
    "athleteName": "Susie Neill",
    "country": "Australia",
    "countryCode": "AUS",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0034",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Swimming",
    "event": "1500m Freestyle Men",
    "medalType": "Gold",
    "athleteName": "Grant Hackett",
    "country": "Australia",
    "countryCode": "AUS",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0035",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Swimming",
    "event": "200m Butterfly Men",
    "medalType": "Gold",
    "athleteName": "Tom Malchow",
    "country": "United States",
    "countryCode": "USA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0036",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Swimming",
    "event": "100m Butterfly Men",
    "medalType": "Gold",
    "athleteName": "Lars Frolander",
    "country": "Sweden",
    "countryCode": "SWE",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0037",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Swimming",
    "event": "200m Backstroke Men",
    "medalType": "Gold",
    "athleteName": "Lenny Krayzelburg",
    "country": "United States",
    "countryCode": "USA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0038",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Swimming",
    "event": "200m Individual Medley Men",
    "medalType": "Gold",
    "athleteName": "Massimiliano Rosolino",
    "country": "Italy",
    "countryCode": "ITA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0039",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Swimming",
    "event": "400m Individual Medley Men",
    "medalType": "Gold",
    "athleteName": "Tom Dolan",
    "country": "United States",
    "countryCode": "USA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0040",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Swimming",
    "event": "200m Breaststroke Men",
    "medalType": "Gold",
    "athleteName": "Domenico Fioravanti",
    "country": "Italy",
    "countryCode": "ITA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0041",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Gymnastics",
    "event": "All-Around Men",
    "medalType": "Gold",
    "athleteName": "Alexei Nemov",
    "country": "Russia",
    "countryCode": "RUS",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0042",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Gymnastics",
    "event": "All-Around Women",
    "medalType": "Gold",
    "athleteName": "Simona Amanar",
    "country": "Romania",
    "countryCode": "ROU",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0043",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Gymnastics",
    "event": "Floor Exercise Women",
    "medalType": "Gold",
    "athleteName": "Elena Zamolodchikova",
    "country": "Russia",
    "countryCode": "RUS",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0044",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Gymnastics",
    "event": "Vault Women",
    "medalType": "Gold",
    "athleteName": "Elena Zamolodchikova",
    "country": "Russia",
    "countryCode": "RUS",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0045",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Badminton",
    "event": "Singles Men",
    "medalType": "Gold",
    "athleteName": "Ji Xinpeng",
    "country": "China",
    "countryCode": "CHN",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0046",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Badminton",
    "event": "Singles Women",
    "medalType": "Gold",
    "athleteName": "Gong Zhichao",
    "country": "China",
    "countryCode": "CHN",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0047",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Judo",
    "event": "48kg Women",
    "medalType": "Gold",
    "athleteName": "Ryoko Tamura",
    "country": "Japan",
    "countryCode": "JPN",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0048",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Tennis",
    "event": "Singles Men",
    "medalType": "Gold",
    "athleteName": "Yevgeny Kafelnikov",
    "country": "Russia",
    "countryCode": "RUS",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0049",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Tennis",
    "event": "Singles Women",
    "medalType": "Gold",
    "athleteName": "Venus Williams",
    "country": "United States",
    "countryCode": "USA",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0050",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Boxing",
    "event": "Super Heavyweight +91kg",
    "medalType": "Gold",
    "athleteName": "Audley Harrison",
    "country": "Great Britain",
    "countryCode": "GBR",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0051",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Boxing",
    "event": "Heavyweight -91kg",
    "medalType": "Gold",
    "athleteName": "Felix Savon",
    "country": "Cuba",
    "countryCode": "CUB",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0052",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Boxing",
    "event": "Light Flyweight -48kg",
    "medalType": "Gold",
    "athleteName": "Brahim Asloum",
    "country": "France",
    "countryCode": "FRA",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0053",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Weightlifting",
    "event": "105kg+ Men",
    "medalType": "Gold",
    "athleteName": "Hossein Rezazadeh",
    "country": "Iran",
    "countryCode": "IRI",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0054",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Rowing",
    "event": "Single Sculls Men",
    "medalType": "Gold",
    "athleteName": "Rob Waddell",
    "country": "New Zealand",
    "countryCode": "NZL",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0055",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Rowing",
    "event": "Single Sculls Women",
    "medalType": "Gold",
    "athleteName": "Ekaterina Karsten",
    "country": "Belarus",
    "countryCode": "BLR",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0056",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Diving",
    "event": "10m Platform Men",
    "medalType": "Gold",
    "athleteName": "Tian Liang",
    "country": "China",
    "countryCode": "CHN",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0057",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Diving",
    "event": "3m Springboard Men",
    "medalType": "Gold",
    "athleteName": "Xiong Ni",
    "country": "China",
    "countryCode": "CHN",
    "gender": "M",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0058",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Diving",
    "event": "10m Platform Women",
    "medalType": "Gold",
    "athleteName": "Laura Wilkinson",
    "country": "United States",
    "countryCode": "USA",
    "gender": "F",
    "isTeamEvent": false
  },
  {
    "id": "OLY-0059",
    "olympicYear": 2000,
    "hostCity": "Sydney",
    "sport": "Diving",
    "event": "3m Springboard Women",
    "medalType": "Gold",
    "athleteName": "Fu Mingmia",
    "country": "China",
    "countryCode": "CHN",
    "gender": "F",
    "isTeamEvent": false
  }
]
